config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  #reviews controller routes
  resources :reviews
  post 'games/:id', to: 'reviews#create'
  post 'reviews/:id', to: 'reviews#update'
  # get 'games/:game_id/reviews/:review_id', to: 'reviews#show'
  # get 'games/:game_id/reviews/new', to: 'reviews#new'
  # get 'reviews/review_id/edit'
  
  #game controller routes
  get 'games/restricted', to: 'games#restricted'
  put "games/:id", to: "games#approved", as: "approve_game"
  resources :games
  get 'library/:user_id', to: 'games#library', as: 'library'
  post "games/:id/buy", to: 'games#buy', as: 'buy'
  get  'games/:id/success', to: 'games#success', as: 'success'
  get  'game/:id/cancel', to: 'games#cancel', as: 'cancel'
  # get 'games/new', to: 'games#new', as: 'games_new'
  # post 'games', to: 'games#create' 
  # get 'games/:game_id', to: 'games#show', as: 'game'
  # get 'games/:game_id/edit', to: 'games#edit', as: 'game_edit'
  # post 'games/:game_id/edit', to: 'games#update'
  
  #user routes
  get 'profiles/:user_id', to: 'users#show', as: 'profile'
  #root route
  root 'games#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
  has_and_belongs_to_many :users
  has_one_attached :picture, dependent: :purge
  has_one_attached :game_folder, dependent: :purge
  has_many :reviews
 
 # validates picture type and that all fields have been filled
  validates :picture, content_type: [:png, :jpg, :jpeg]
  validates :game_folder, content_type: [:zip]

  validates_presence_of :title, :picture, :description, :price, :game_folder
  validates_uniqueness_of :title
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:buy]
  before_action :authenticate_user!, except: [:index, :show, :edit]
  before_action :set_games, only: [:index]
  before_action :set_user, only: [:library]
  before_action :set_game, only: [:buy, :update, :destroy, :success, :approved]
  
  def index
  end
  
  def library
    @games = @user.games
  end

  def show
    if params[:id].to_i > Game.last.id
      redirect_to games_path
      flash[:alert] = "Could not find a game by id #{params[:id]}"
    else
      @game = Game.find(params[:id])
      @reviews = Review.where(game_id: params[:id])
    end
  end

  def edit
    @game = Game.find(params[:id])
    @game_owner = User.find_by_username(@game.owner)
    if !user_signed_in?
      redirect_to new_user_session_path()
    else
      if current_user.id != @game_owner.id
        redirect_to games_path()
      end
    end
  end

  def update
    @game.update(set_game_params)
    redirect_to game_path(@game.id)
    # render json: params
  end

  def new
    @game = Game.new
  end
  
  def create
    @user = signed_in_user
    @game = Game.new(set_game_params)
    @game.owner = current_user.username
    @game.approved = false
    if @game.save
      redirect_to game_path(@game.id)
    else
      flash[:form_errors] = @game.errors.full_messages
      render "new"
      # redirect_to new_game_path
      # flash[:error] = "Must fill out every area in the form"
    end
  end

  def destroy
    @game.destroy
    redirect_to games_path()
  end
  
  def buy
    Stripe.api_key = ENV['STRIPE_API_KEY']
    session = Stripe::Checkout::Session.create({
      payment_method_types: ['card'],
      mode: 'payment',
      success_url: success_url(params[:id]),
      cancel_url: cancel_url(params[:id]),
      line_items: [
        {
          price_data: {
            currency: 'aud',
            product_data: {
              name: @game.title
            },
            unit_amount: (@game.price.to_f * 100).to_i
          },
          quantity: 1
        }
      ]
    })

    render json: session
  end

  def success
    @user = User.find(current_user.id)
    @user.games.push(@game)
    redirect_to games_path
    flash[:alert] = "Your purchase was successful!"
  end

  def cancel
    redirect_to games_path
    flash[:alert] = "Payment was unsuccessful!"
  end
  
  def restricted
    if user_signed_in?
      if current_user.has_role?(:admin)
        @games = Game.where(approved: false)
      else
        redirect_to games_path
        flash[:alert] = "You dont have access to this page"
      end
    else
      redirect_to games_path
      flash[:alert] = "You dont have access to this page"
    end
  end

  def approved
    @game.update(approved: true)
    @user = User.find_by_username(@game.owner)
    @user.games.push(@game)
    # redirect_to game_path(@game.id)
    redirect_to games_restricted_path
  end

  private

  def add_game

  end

  def set_game_params
    params.require(:game).permit(:title, :description, :price, :picture, :game_folder)
  end
  
  def set_game
    @game = Game.find(params[:id])
  end 

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_games
    @games = Game.where(approved: true)
  end
  
  def signed_in_user
    @user = User.find(current_user.id)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/edit.html.erb
<h1>Edit <%= @game.title %></h1>

<%= form_with model: @game, local: true do |f| %>
<div class="field">
    <%= f.label :picture %><br />
    <%= f.file_field :picture, accept: 'image/jpeg, image/png, image/jpg' %>
</div>
<div>
    <%= image_tag @game.picture, class: "game-pic" if @game.picture.attached? %>
</div>
<div>
    <%= f.label :title %>
    <%= f.text_field :title %>
</div>
<div>
    <%= f.label :description %>
    <%= f.text_area :description %>
</div>
<div>
    <%= f.label :price %>
    <%= f.number_field :price, min: 0, step: 0.01 %>      
</div>
<div>
    <p><%= link_to 'Delete', game_path(@game.id), method: :delete, data: { confirm: "Are you really realy sure??" } %></p>
    <%= f.submit "Edit" %>
</div>
<% end %>

app/views/games/index.html.erb
<div>
    <h1 class="display-2">Welcome To Balance Games</h1>
</div>
<div class="row">
    <% @games.each do |game| %>
        <div class="card col-lg-3" style="width: 20rem;">
            <% if game.picture.attached? %>
                <%= image_tag game.picture, class: "card-img-top" %>
            <% end %>
            <div class="card-body">
                <h5 class="card-title"><%= game.title %></h5>
                <p class="card-text"><%= game.description %></p>
                <%=link_to "More", game_path(game.id), class: "btn btn-primary" %>
            </div>
        </div>
    <% end %>
</div>
   

<%= link_to "Submit Your Games Here!", new_game_path %>
<% if user_signed_in? %>
    <% if current_user.has_role?(:admin) %>
        <h1><%= link_to "View Games Waiting Approval", games_restricted_path %></h1>
    <% end %>
<% end %>

app/views/games/library.html.erb
<h1><%= @user.username %>'s Games</h1>
<div class="row">
    <% @games.each do |game| %>
        <div class="card col-lg-3" style="width: 20rem;">
            <% if game.picture.attached? %>
                <%= image_tag game.picture, class: "card-img-top" %>
            <% end %>
            <div class="card-body">
                <h5 class="card-title"><%= game.title %></h5>
                <%=link_to "More", game_path(game.id), class: "btn btn-primary" %>
                <% if current_user.id == @user.id %>
                    <%= link_to "Download #{game.title}", rails_blob_path(game.game_folder, disposition: 'attachment'), class: "btn btn-primary" %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

app/views/games/new.html.erb
<h1>Submit a game you have created!</h1>

<%= form_with model: @game, local: true do |f| %>
    <% if flash[:form_errors] %>
        <% flash[:form_errors].each do |error| %>
            <p><%= error %></p>
        <% end %>
    <% end %>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <div>
        <%= f.label :description %>
        <%= f.text_area :description %>
    </div>
    <div>
        <%= f.label :price %> $:
        <%= f.number_field :price, min: 0, step: 0.01%>      
    </div>
    <div >
        <%= f.label :picture %><br />
        <%= f.file_field :picture, accept: 'image/jpeg, image/png, image/jpg' %>
    </div>
    <div >
        <%= f.label :game_folder %>     
        <%= f.file_field :game_folder, accept: 'application/zip' %>
    </div>
    <!-- <div>
        <%# f.label :menus %>
        <%# f.collection_check_boxes :menu_ids, @menus, :id, :title %>
    </div> -->
    <div>
        <%= f.submit "Submit" %>
    </div>
<% end %>

app/views/games/restricted.html.erb
<h1>admin page</h1>

<% @games.each do |game| %>
    <div>
        <h1><%=link_to game.title, game_path(game.id) %></h1>
        <% if game.picture.attached? %>
            <%= image_tag game.picture, class: "game-pic" %>
        <% end %>
        <%= link_to "Approve", approve_game_path(game.id), method: :put, class: "btn btn-secondary" %>
        <%= button_to "Delete", game_path(game.id), method: :delete, class: "btn btn-danger" %>
    </div>
<% end %>

app/views/games/show.html.erb
<div>
    <h1><%= @game.title %></h1>
    <% if @game.picture.attached? %>
        <%= image_tag @game.picture, class: 'show-game-pic' %>
    <% end %>
</div>
<div>
    <h4>Developer: <%= @game.owner %></h4>
    <h4><%= @game.description %></h4>
    <h4>Rating: <%= @game.avg_rating %></h4>
    <h4>Price: <%= "$%.2f" % @game.price %></h4>
</div>
<% if user_signed_in? %>
    <% if current_user.username == @game.owner %>
        <p><%= link_to 'Edit Game', edit_game_path(@game.id) %></p>
    <% end %>   
<% end %>
<% if user_signed_in? %>
    <% if @game.approved == true %>
        <% if current_user.games.include?(@game) == false %>
            <p><button id="buynow-button">Buy Now!</button></p>
        <% end %>
    <% else %>
    <h3>This game is waiting approval!</h3>
    <% end %>
<% else %>
    <h2><%= link_to "Login to purchase this game!", new_user_session_path %></h2>
<% end %>

<script src="https://js.stripe.com/v3/"></script>

<script>
    const stripe = Stripe("<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>")
    const buyButton = document.getElementById('buynow-button')

    buyButton.addEventListener('click', function(){
        fetch('<%= buy_path(@game.id) %>', {
            method: 'POST'
        })
        .then(function(response){
            return response.json()
        })
        .then(function(session){
            return stripe.redirectToCheckout({sessionId: session.id})
        })
    })
</script>

<% if user_signed_in? %>
    <% current_user.games.each do |game| %>
        <% if game.id == @game.id %>
            <h1>Leave a review! </h1>
            <%= form_with model: @game, local: true do |f| %>
                <% if flash[:form_errors] %>
                    <% flash[:form_errors].each do |error| %>
                        <p><%= error %></p>
                    <% end %>
                <% end %>
            <% end %>
            <%= form_with model: @review, local: true do |f| %>
                <div>
                    <%= f.label :title %>
                    <%= f.text_field :title %>
                </div>
                <div>
                    <%= f.label :content %>
                    <%= f.text_area :content %>
                </div>
                <div>
                    <%= f.label :rating %>
                    <%= f.number_field :rating, min: 0, max: 5, step: 0.50 %>
                </div>
                <div>
                    <%= f.submit "Submit Review" %>
                </div>
            <% end %> 
        <% end %>
    <% end %>
<% else %>
    <h2>Buy this game to leave a review!</h2>
<% end %>

<% @reviews.each do |review| %>
    <div class="card">
        <div class="card-header">
            <h5><%= review.user %> </h3>
        </div>
        <div class="card-body">
            <h2><%= review.title %> </h2>
            <h4><%= review.content %></h4> 
            <h4>Rating: <%= "%.1f" % review.rating %></h4> 
            <% if user_signed_in? %>
                <% if current_user.username == review.user %>
                    <h6><%= link_to "Edit", edit_review_path(review.id), class: "btn btn-primary" %></h6>
                <% end %>
            <% end %>   
        </div>
    </div>
<% end %>