config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  #reviews controller routes
  resources :reviews
  post 'games/:id', to: 'reviews#create'
  post 'reviews/:id', to: 'reviews#update'
  # get 'games/:game_id/reviews/:review_id', to: 'reviews#show'
  # get 'games/:game_id/reviews/new', to: 'reviews#new'
  # get 'reviews/review_id/edit'
  
  #game controller routes
  get 'games/restricted', to: 'games#restricted'
  put "games/:id", to: "games#approved", as: "approve_game"
  resources :games
  get 'library/:user_id', to: 'games#library', as: 'library'
  post "games/:id/buy", to: 'games#buy', as: 'buy'
  get  'games/:id/success', to: 'games#success', as: 'success'
  get  'game/:id/cancel', to: 'games#cancel', as: 'cancel'
  # get 'games/new', to: 'games#new', as: 'games_new'
  # post 'games', to: 'games#create' 
  # get 'games/:game_id', to: 'games#show', as: 'game'
  # get 'games/:game_id/edit', to: 'games#edit', as: 'game_edit'
  # post 'games/:game_id/edit', to: 'games#update'
  
  #user routes
  get 'profiles/:user_id', to: 'users#show', as: 'profile'
  #root route
  root 'games#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_reviews, only: [:show]
  before_action :find_review, only: [:edit, :update, :destroy]
  def show
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(permit_params)
    @review.user = current_user.username
    @review.game_id = params[:id]
    if @review.save
      update_game_rating(@review.game_id)
      redirect_to game_path(@review.game_id)
    else
      flash[:form_errors] = @review.errors.full_messages
      redirect_to game_path(params[:id])
    end
  end

  def edit
    if !user_signed_in?
      redirect_to new_user_session_path()
    else
      if current_user.username != @review.user
        redirect_to games_path()
      end
    end
  end

  def update
    @review.update(permit_params)
    redirect_to game_path(@review.game_id)
    # render json: params
  end

  def destroy
    @review.destroy
    redirect_to games_path()
  end

  private

  def permit_params
    params.permit(:title, :content, :rating)
  end

  def find_review
    @review = Review.find(params[:id])
  end

  def set_reviews
    @reviews = Review.where(params[:id])
  end

  def update_game_rating(game_id)
    avg = 0
    @reviews = Review.where(game_id: game_id)
    @reviews.each do |review|
      avg += review.rating
    end
    avg = avg / @reviews.size
    @game = Game.find(game_id)
    @game.update(avg_rating: avg)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/edit.html.erb
<%= form_with model: @review, local: true do |f| %>
        <div>
            <%= f.label :title %>
            <%= f.text_field :title %>
        </div>
        <div>
            <%= f.label :content %>
            <%= f.text_area :content %>
        </div>
        <div>
            <%= f.label :rating %>
            <%= f.number_field :rating, min: 0, max: 5, step: 0.50 %>
        </div>
        <div>
            <%= f.submit "Edit Review" %>
            <h3><%= link_to 'Delete', review_path(@review.id), method: :delete, data: { confirm: "Are you really realy sure??" } %></h3>

        </div>
    <% end %> 

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>