config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  #reviews controller routes
  resources :reviews
  post 'games/:id', to: 'reviews#create'
  post 'reviews/:id', to: 'reviews#update'
  # get 'games/:game_id/reviews/:review_id', to: 'reviews#show'
  # get 'games/:game_id/reviews/new', to: 'reviews#new'
  # get 'reviews/review_id/edit'
  
  #game controller routes
  get 'games/restricted', to: 'games#restricted'
  put "games/:id", to: "games#approved", as: "approve_game"
  resources :games
  get 'library/:user_id', to: 'games#library', as: 'library'
  post "games/:id/buy", to: 'games#buy', as: 'buy'
  get  'games/:id/success', to: 'games#success', as: 'success'
  get  'game/:id/cancel', to: 'games#cancel', as: 'cancel'
  # get 'games/new', to: 'games#new', as: 'games_new'
  # post 'games', to: 'games#create' 
  # get 'games/:game_id', to: 'games#show', as: 'game'
  # get 'games/:game_id/edit', to: 'games#edit', as: 'game_edit'
  # post 'games/:game_id/edit', to: 'games#update'
  
  #user routes
  get 'profiles/:user_id', to: 'users#show', as: 'profile'
  #root route
  root 'games#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketPlace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous" defer></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous" defer></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous" defer></script>

    <link href="https://getbootstrap.com/docs/4.5/examples/starter-template/starter-template.css" rel="stylesheet">
  </head>

  <body>
    <% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p class="alert"><%= flash[:alert] %></p>
    <% end %>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <%= link_to "Balance Games", games_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
            <% if user_signed_in? %>
              <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Menu</a>
              <div class="dropdown-menu" aria-labelledby="dropdown01">
                <%= link_to "Library", library_path(current_user.id), class: "dropdown-item" %>
                <%= link_to "Profile", profile_path(current_user.id), class: "dropdown-item" %>
                <%= link_to "Log Out", destroy_user_session_path, method: 'delete', class: "dropdown-item" %>
              </div>
            <% else %>
              <li class="nav-item"><%= link_to "login", new_user_session_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "Register", new_user_registration_path, class: "nav-link" %></li>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container flex-nowrap">
      <%= yield %>
  </div>
  </body>
</html>